language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=9bccb67803c7ea15aaffdd8cfc766226858ff51bd82295af2fdd3175a2dadcb6
matrix:
  include:
    - node_js: '12'
cache:
  directories: [node_modules]
install:
  yarn
after_success: yarn coverage
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test
afterscript:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESUL
